services:
  web:
    build: .
    command: ["sh", "-c", "/usr/bin/wait-for-it.sh db:5432 -- python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"]
    volumes:
      - static_volume:/app/static
    env_file:
      - .env.production
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=stockvinos
      - POSTGRES_USER=stockvinos_user
      - POSTGRES_PASSWORD=8rwiAA6kDALmp76fGDfgoJNldEE

volumes:
  static_volume:
  postgres_data:
