# Generated by Django 5.0.6 on 2024-06-19 18:37

import django.core.validators
import django.db.models.deletion
import stock.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^\\S+', 'Este campo no puede estar vacío.')], verbose_name='Sucursal')),
                ('address', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^\\S+', 'Este campo no puede estar vacío.')], verbose_name='Direccion')),
                ('telephone', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Número de teléfono no válido.')], verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='BranchStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock en Sucursal')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(unique=True, validators=[stock.models.validate_positive], verbose_name='DNI')),
                ('is_active', models.BooleanField(default=True, verbose_name='En actividad')),
                ('cuil', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='El CUIL debe estar en el formato NN-NNNNNNNN-N', regex='^\\d{2}-\\d{7,8}-\\d$')], verbose_name='CUIL')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.branch', verbose_name='Sucursal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('variety', models.CharField(choices=[('Malbec', 'Malbec'), ('Cabernet', 'Cabernet'), ('Merlot', 'Merlot'), ('Chardonnay', 'Chardonnay'), ('Syrah', 'Syrah'), ('Pinot Noir', 'Pinot Noir'), ('Sauvignon Blanc', 'Sauvignon Blanc')], max_length=20, verbose_name='Varietal')),
                ('description', models.TextField(max_length=500, verbose_name='Descripcion')),
                ('vintage', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)], verbose_name='Cosecha')),
                ('branches', models.ManyToManyField(through='stock.BranchStock', to='stock.branch', verbose_name='Sucursales')),
            ],
        ),
        migrations.AddField(
            model_name='branchstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product'),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[stock.models.validate_positive], verbose_name='Cantidad')),
                ('typeof', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], max_length=5, verbose_name='Tipo')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.branch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.employee', verbose_name='Empleado')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.product')),
            ],
        ),
    ]
