# Generated by Django 5.0.6 on 2024-06-12 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='En actividad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='variety',
            field=models.CharField(choices=[('Malbec', 'Malbec'), ('Cabernet', 'Cabernet'), ('Merlot', 'Merlot'), ('Chardonnay', 'Chardonnay'), ('Syrah', 'Syrah'), ('Pinot Noir', 'Pinot Noir'), ('Sauvignon Blanc', 'Sauvignon Blanc')], max_length=20, verbose_name='Varietal'),
        ),
        migrations.AlterField(
            model_name='record',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.branch'),
        ),
    ]
