# Generated by Django 5.0.6 on 2024-06-18 02:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^\\S+', 'Este campo no puede estar vacío.')], verbose_name='Sucursal'),
        ),
    ]
