# Generated by Django 5.0.6 on 2024-06-13 15:11

import stock.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_employee_is_active_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, validators=[stock.models.validate_positive], verbose_name='Cantidad Disponible'),
        ),
    ]
