# Generated by Django 5.0.6 on 2024-06-22 15:29

from django.db import migrations

def create_groups_and_permissions(apps, schema_editor):
    from django.core.management import call_command
    call_command('add_groups')

def add_users_to_grous(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Group = apps.get_model('auth', 'Group')

    user1 = User.objects.get(username='empleado1')
    user2 = User.objects.get(username='empleado2')

    bmanagers = Group.objects.get(name='System admins')
    workers = Group.objects.get(name='System admins')

    bmanagers.user_set.add(user1)
    workers.user_set.add(user2)


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20240619_1839'),
    ]

    operations = [
        migrations.RunPython(create_groups_and_permissions),
        migrations.RunPython(add_users_to_grous),
    ]
