# Generated by Django 5.0.6 on 2024-06-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
